services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
  request:
    build:
      context: ./product-request
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitMQ
  receiver:
    build:
      context: ./product-receiver
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - request